// -*- C++ -*-
//
// SOCK_CODgram.inl,v 4.2 2005/10/28 16:14:55 ossama Exp

ACE_BEGIN_VERSIONED_NAMESPACE_DECL

ACE_INLINE
ACE_SOCK_CODgram::ACE_SOCK_CODgram (void)
{
  ACE_TRACE ("ACE_SOCK_CODgram::ACE_SOCK_CODgram");
}

ACE_INLINE
ACE_SOCK_CODgram::~ACE_SOCK_CODgram (void)
{
  ACE_TRACE ("ACE_SOCK_CODgram::~ACE_SOCK_CODgram");
}

ACE_END_VERSIONED_NAMESPACE_DECL
