// -*- C++ -*-
// Version.h,v 4.378 2006/03/05 17:12:38 bugzilla Exp

// This is file was automatically generated by $ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 5
#define ACE_BETA_VERSION 0
#define ACE_VERSION "5.5"

