import glob

dst = '../lib/'

target = 'VASTATEsim'
source = glob.glob('*.cpp')

inc1 = '../common/'
inc2 = '../VASTnet/'
inc3 = '../VAST/'
inc4 = '../VASTATE/'
inc5 = '../VASTsim/'
inc = [inc1, inc2, inc3, inc4, inc5, '.']

env = Environment(CPPPATH = ['.'])
env.Append(CCFLAGS = '-O3')

static_build = ARGUMENTS.get('static', 0)

targetlib = None
if int(static_build):
	env.Append(LINKFLAGS = '-static')
	env.StaticLibrary(target, source)
	targetlib = 'lib' + target + '.a'
else:
	env.SharedLibrary(target, source)
	targetlib = 'lib' + target + '.so'

Repository(inc)

ret = env.Install(dst, targetlib)
env.Default(ret)
    
